-   id: jira
    name: Jira issue commit message
    description: Add the issue ID to the body of the commit
    entry: src/gjira.py
    language: python
    always_run: true
    stages: [prepare-commit-msg]
