repos:
-   repo: meta
    hooks:
    -   id: identity
-   repo: .
    rev: HEAD
    hooks:
    -   id: gjira
        language_version: python3
        args: ['--board=EMMENTAL', '--regex=ISSUE-\d+']
    -   id: gjira-check-branch
        language_version: python3
        args: ["--regex=^(feat|refactor|fix|chore)/.*$|^(master|dev(elop)?)$"]
