repos:
-   repo: meta
    hooks:
    -   id: identity
-   repo: .
    rev: HEAD
    hooks:
    -   id: gjira
        language_version: python3
        args: ['--board=EMMENTAL', '--regex=ISSUE-\d+']
    -   id: gjira-check-branch
        language_version: python3
        args: ["--regex=^(master|dev(elop)?|release-\d+(\.\d+)*|new-staging|(SKYR-\d+_[a-z]+(-[a-z]+)*))$"]
